version: "3.7"

volumes:
  grafana_data: {}
  prometheus_data: {}
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 512M
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana-oss:9.2.5
    container_name: grafana
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 512M
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/grafana.ini:/grafana.ini
    environment:
      - GF_USERS_ALLOW_SIGN_UP=true
    ports:
      - "8888:3000"
