---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    haproxy_rpm: https://repo.vsk.ru/repository/yum-local/haproxy/2.0/haproxy-2.0.23-1.el7.x86_64.rpm
  roles:
    - kee.haproxy
