---
# HAProxy common
haproxy_rpm: https://repo.vsk.ru/repository/yum-local/haproxy/2.0/haproxy-2.0.23-1.el7.x86_64.rpm
haproxy_config_dir: /etc/haproxy
haproxy_certs_dir: /etc/haproxy/certs
haproxy_certs: []
  #- 'certs/example1.com-chain.pem'
  #- 'certs/example2.com-chain.pem'

# Global
haproxy_socket: /var/run/haproxy.stat 
haproxy_chroot: /var/empty
haproxy_user: haproxy
haproxy_group: haproxy

# Extra Global
haproxy_global_vars:
  - 'maxconn 20000'
  - 'ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384'
  - 'ssl-default-bind-options prefer-client-ciphers no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets'
  - 'ssl-default-server-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384'
  - 'ssl-default-server-options no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets'
  - 'ssl-dh-param-file {{ haproxy_config_dir }}/dhparam'
  - '#nbproc 1'
  - '#nbthread 2'
  #- 'cpu-map auto:1/1-2 0-1'

# Frontend HTTP
haproxy_frontend:
  - name: http
    description: HTTP Frontend
    mode: http
    frontend_vars:
      - 'bind :80' 
      - ''
      - 'maxconn 10000' 
      - 'default_backend default'

# Frontend HTTPS
#haproxy_frontend:
#  - name: www.example.com
#    description: HTTPS Frontend
#    mode: http
#    frontend_vars:
#      - 'bind :80' 
#      - 'bind :443 ssl crt {{ haproxy_certs_dir }}/ alpn h2,http/1.1' 
#      - 'maxconn 10000' 
#      - ''
#      - 'redirect scheme https code 301 if !{ ssl_fc }'
#      - 'http-request set-header X-Forwarded-Proto https'
#      - 'option forwardfor except 127.0.0.1'
#      - ''
#      - 'default_backend default'
#      - 'http-response set-header Strict-Transport-Security max-age=63072000'

# Backend 
haproxy_backend:
  - name: default
    description: Default Backend 
    mode: http
    backend_vars:
      - 'balance roundrobin'
      - 'option httpchk GET /health'
      - 'server srv1 127.0.0.1:8001 check inter 1000'
      - 'server srv2 127.0.0.1:8002 check inter 1000'
      - 'server srv3 127.0.0.1:8003 check inter 1000'
